python -m models.bert --target "dspln_PSYCHIATRY_0"
python -m models.bert --target "dspln_SOCIALWORK_0"
python -m models.bert --target "need_emots_1"
python -m models.bert --target "need_emots_2"
python -m models.bert --target "need_infos_1"
python -m models.bert --target "need_infos_2"
python -m models.bert --target "surv_mo_6"
python -m models.bert --target "surv_mo_36"
python -m models.bert --target "surv_mo_60"

python -m models.bert --target "dsplnmulti_SOCIALWORK_2"
python -m models.bert --target "dsplnmulti_PSYCHIATRY_2"