python -m models.bow --target "dsplnic_PSYCHIATRY_60_I" --table "compare_stages" --epochs 1 --table_extra "I & 4078"
python -m models.cnn --target "dsplnic_PSYCHIATRY_60_I" --table "compare_stages" --table_extra "I & 4078"
python -m models.bow --target "dsplnic_PSYCHIATRY_60_II" --table "compare_stages" --epochs 1 --table_extra "II & 5535"
python -m models.cnn --target "dsplnic_PSYCHIATRY_60_II" --table "compare_stages" --table_extra "II & 5535"
python -m models.bow --target "dsplnic_PSYCHIATRY_60_III" --table "compare_stages" --epochs 1 --table_extra "III & 3809"
python -m models.cnn --target "dsplnic_PSYCHIATRY_60_III" --table "compare_stages" --table_extra "III & 3809"
python -m models.bow --target "dsplnic_PSYCHIATRY_60_IV" --table "compare_stages" --epochs 1 --table_extra "IV & 3638"
python -m models.cnn --target "dsplnic_PSYCHIATRY_60_IV" --table "compare_stages" --table_extra "IV & 3638"
python -m models.bow --target "dsplnic_PSYCHIATRY_60_nonmet" --table "compare_stages" --epochs 1 --table_extra "I+II+III & 13422"
python -m models.cnn --target "dsplnic_PSYCHIATRY_60_nonmet" --table "compare_stages" --table_extra "I+II+III & 13422"