python -m models.bow --target "need_emots_4_I" --table "compare_stages_emots" --epochs 1 --table_extra "I & 4078"
python -m models.cnn --target "need_emots_4_I" --table "compare_stages_emots" --table_extra "I & 4078"
python -m models.bow --target "need_emots_4_II" --table "compare_stages_emots" --epochs 1 --table_extra "II & 5535"
python -m models.cnn --target "need_emots_4_II" --table "compare_stages_emots" --table_extra "II & 5535"
python -m models.bow --target "need_emots_4_III" --table "compare_stages_emots" --epochs 1 --table_extra "III & 3809"
python -m models.cnn --target "need_emots_4_III" --table "compare_stages_emots" --table_extra "III & 3809"
python -m models.bow --target "need_emots_4_IV" --table "compare_stages_emots" --epochs 1 --table_extra "IV & 3638"
python -m models.cnn --target "need_emots_4_IV" --table "compare_stages_emots" --table_extra "IV & 3638"
python -m models.bow --target "need_emots_4_nonmet" --table "compare_stages_emots" --epochs 1 --table_extra "I+II+III & 13422"
python -m models.cnn --target "need_emots_4_nonmet" --table "compare_stages_emots" --table_extra "I+II+III & 13422"